### PR TITLE
change queue client to IMessageReceiver

### PR DESCRIPTION
**Pull request by mdayican**
### Change description ###

change queue client to IMessageReceiver
IMessageReceiver seems more powerful.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by mdayican** [comment]
> Could you please specify what `IMessageReceiver seems more powerful.` means and how it will be useful ?
> 
> Also if you use `IMessageReceiver` could you manually dead letter messages or control the delivery count of the message ?

I did not do deep search, we mostly used IMessageReceiver to receive messages from queue with spring schedule and do manual operations like dead lettering and we used queueClient with listener.

**Comment by mdayican** [comment]
> we would still need `QueueClient` to register `IMessageHandler` and provide `MessageHandlerOptions` for non auto completion technique (or flag if such and deal manually then). and also have assurance connection is up and ready to be used as we have experienced the latency and message handler could not be registered straight away

we will not register message handler.we will poll with spring schedule.

**Comment by doncem** [comment]
Oh yes, my bad

**Comment by mdayican** [comment]
> Oh yes, my bad

actually  that is the reason I am changing this. IMessageHandler looks better for manual operations.

**Pull request merged**
